#!/usr/bin/env bash

#You'll need to log into Azure first 'sudo az acr login'
cd docker
sudo az acr login --name itacontainerregistry
sudo docker login itacontainerregistry.azurecr.io #use container username and access key
sudo docker build -t itacontainerregistry.azurecr.io/fta-tariff-tool-dataloader .
sudo docker push itacontainerregistry.azurecr.io/fta-tariff-tool-dataloader
# sudo az container delete --resource-group ITA_DataServices --name fta-tariff-tool-dataloader --yes
# sudo az container create --resource-group ITA_DataServices --name fta-tariff-tool-dataloader \
#     --image itacontainerregistry.azurecr.io/fta-tariff-tool-dataloader:latest --dns-name-label fta-tariff-tool-dataloader --ports 80 \
#     --location eastus --registry-username ITAContainerRegistry --registry-password $TARIFFTOOL_AZURE_CONTAINER_KEY \
#     --environment-variables 'TARIFFTOOL_AZURE_STORAGE_ACCOUNT'=$TARIFFTOOL_AZURE_STORAGE_ACCOUNT \
#     'TARIFFTOOL_AZURE_STORAGE_ACCOUNT_KEY'=$TARIFFTOOL_AZURE_STORAGE_ACCOUNT_KEY \
#     'TARIFFTOOL_AZURE_STORAGE_CONTAINER'=$TARIFFTOOL_AZURE_STORAGE_CONTAINER \
#     'TARIFFTOOL_AZURE_OAUTH_CLIENT_ID'=TARIFFTOOL_AZURE_OAUTH_CLIENT_ID \
#     'TARIFFTOOL_AZURE_OAUTH_CLIENT_SECRET'=TARIFFTOOL_AZURE_OAUTH_CLIENT_SECRET \
#     'TARIFFTOOL_AZURE_OAUTH_TENANT_ID'=TARIFFTOOL_AZURE_OAUTH_TENANT_ID

#FYI: Registry credentials are autogenerated and can be procured from portal.azure.com

#to view logs
#az container logs --resource-group ITA_DataServices --name ftatarifftooldataloader
cd ..

kubectl apply -f kube-config.yml
