#!/usr/bin/env bash
cd docker
sudo az acr login --name itatarifftool
sudo docker build -t itatarifftool.azurecr.io/ita-tariff-tool .
sudo docker push itatarifftool.azurecr.io/ita-tariff-tool
sudo az container create --resource-group ita-tariff-tool-resources --name itatarifftool --image itatarifftool.azurecr.io/ita-tariff-tool:latest --dns-name-label ita-tariff-tool-demo --ports 8080 --location westus --registry-username itatarifftool
#FYI: Registry credentials are autogenerated and can be procured from portal.azure.com

#to view logs
#az container logs --resource-group ita-tariff-tool-resources --name itatarifftool
cd ..