spring:
  profiles:
    active: development
terrafreights:
  version: 1.0.0
---
spring:
  profiles: production
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: b6c6f905-01c8-417e-a94a-785608a53cd7
            client-secret: 55-Irl*+npB]NyWtx6xOauaQv6UX=_zy
azure:
  activedirectory:
    tenant-id: 787661a1-5142-41c0-bcc5-c2c9080781e5
    active-directory-groups: EDSP
terrafreights:
  version: 1.0.0
  azure-storage-account: ${TARIFFTOOL_AZURE_STORAGE_ACCOUNT}
  azure-storage-account-key: ${TARIFFTOOL_AZURE_STORAGE_ACCOUNT_KEY}
  azure-storage-container: ${TARIFFTOOL_AZURE_STORAGE_CONTAINER}