spring:
  profiles:
    active: development
  jpa:
    show-sql: false
    format_sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
  h2:
    console:
      enabled: true
      path: /h2-console
      mode: MySQL
  datasource:
    url: jdbc:h2:mem:terrafreights;MODE=MySQL
    username: SA
    password:

---

spring:
  profiles: production
  jpa:
    show-sql: false
    format_sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
terrafreights:
  properties:
    korea_csv: https://s3.amazonaws.com/tariffs/20190430/Korea.csv
    australia_csv: https://s3.amazonaws.com/tariffs/20190502/Australia.csv
